### ISSUE TITLE
amd->slim format doesn't work when define() calls are nested

### ISSUE THREAD

**Issue by matthewp** [stealjs/transpile#104]
lodash looks like below.

```js
  // Some AMD build optimizers, like r.js, check for condition patterns like:
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    // Expose Lodash on the global object to prevent errors when Lodash is
    // loaded by a script tag in the presence of an AMD loader.
    // See http://requirejs.org/docs/errors.html#mismatch for more details.
    // Use `_.noConflict` to remove Lodash from the global object.
    root._ = _;

    // Define as an anonymous module so, through path mapping, it can be
    // referenced as the "underscore" module.
    define(function() {
      return _;
    });
  }
  // Check for `exports` after `define` in case a build optimizer adds it.
  else if (freeModule) {
    // Export for Node.js.
    (freeModule.exports = _)._ = _;
    // Export for CommonJS support.
    freeExports._ = _;
  }
```

This is because [this check](https://github.com/stealjs/transpile/blob/5e05798b4156276e5a06d02bd87a2e24fa7d629a/lib/amd/slim.js#L54) is falsey.

@m-mujica is this because we only support AMD when it wraps all of the code? This is an intentional limitation for now?

**Comment by m-mujica** [comment]
Yeah, the AMD->SLIM transpiler lives in fantasy land where weir UMD definitions don't exist :(

**Comment by matthewp** [comment]
What's the reason we have trouble with UMD exactly?

**Comment by m-mujica** [comment]
the reason is just an oversight on my side probably, I did not account for modules defined like that.

**Comment by matthewp** [comment]
Ok, I was thinking that maybe it was because we replace the define(fn) with `[1, function(){}]` and UMD doesn't fit that model well. I feel like we did talk about UMD...

One possible solution is that we add something like `var define = function(fn) { stealModule.exports = fn(); };` to the top of the module so the UMD define calls will set the stealModule export.

**Comment by m-mujica** [comment]
@matthewp we talked about this when dealing with jquery's IIFE https://github.com/stealjs/transpile/issues/84

But that shim is only applied if an IIFE is detected; let me check if I can steal the logic from r.js to detect the umd code.

**Comment by matthewp** [comment]
Yeah, I suggested the same thing in that issue but you didn't respond. :D .

**Comment by m-mujica** [comment]
haha, that's what you get for asking me to add estimates :P 

I did implement the shim though https://github.com/stealjs/transpile/pull/85/files#diff-0f715189dfb1fe907aa8e03bb208503a I just need to make the condition broader and do the same thing for code using the UMD wrapper.

**Comment by m-mujica** [comment]
> Yeah, I suggested the same thing in that issue but you didn't respond. :D .

oh, after re-reading I think I understand now :P

**Comment by matthewp** [comment]
Got it, cool!
