### ISSUE TITLE
Cannot turn sourcemaps off in an ES6 to AMD transform

### ISSUE THREAD

**Issue by m-mujica** [stealjs/transpile#144]

**Comment by matthewp** [comment]
This is unrelated to the recent change? This happens even without forceES5 set to false?

**Comment by m-mujica** [comment]
Yes, unrelated https://github.com/stealjs/transpile/blob/master/lib/es6_amd.js#L13

It's always on for that specific transform... I need to turn it off, the package to get the AST does not handle the ES2015 nodes.
