### ISSUE TITLE
global "polyfill" when transpiling CJS to other formats  

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/transpile#32]
In one of my CJS files, I have:

```js
global.XMLHttpRequest = function(){ ... }
```

When I export this to the "global" format ... things break.  It would be nice if we can handle things like this for the user.  Another example would be `__dirname`.  We could hard-code what the __dirname was.

**Comment by matthewp** [comment]
There's  `System.global`

**Comment by justinbmeyer** [comment]
Even if there's no system?

**Comment by matthewp** [comment]
I encountered this.  Our CommonJS plugin does this:

```js
(function(global, exports, module, require, __filename, __dirname){
global.XMLHttpRequest = function(){ ... }
})(_g.global, ...)
```

So we should be wrapping the commonjs loads with something like this.

**Comment by matthewp** [comment]
WebPack injects this for the global:

```js
function() { return this; }()
```

**Comment by matthewp** [comment]
Both webpack and browserify only inject `global` and `__dirname` if they are being used.
