### ISSUE TITLE
AMD -> SLIM not working for jQuery-like IIFE

### ISSUE THREAD

**Issue by m-mujica** [stealjs/transpile#84]

**Comment by matthewp** [comment]
@m-mujica can you add an estimate (an wait until after you've fixed it if you want)

**Comment by m-mujica** [comment]
@matthewp I think there is an issue with jquery being detected as amd, and that's why it feels awkward trying to fit jquery with the regular amd algorithm.

jQuery's wrapper looks like the one below:

```js
(function(global, factory) {
  if (typeof module === "object" && typeof module.exports === "object") {
    factory(global, true);
  } else {
    factory(global);
  }
})(typeof window !== "undefined" ? window : this, function(window, noGlobal) {
  var jQuery = {};

  if (window.define && define.amd) {
    define("jquery", [], function() {
      return jQuery;
    });
  }

  return jQuery;
});
```

I think a slim version of that would be:

```js
[
  "jquery",
  function(stealRequire, stealExports, stealModule) {
    stealModule.exports = (function() {
		// eval jquery's content somehow and return it?
    })(window);
  }
]
```

I'm having trouble figuring out how to make it work with the amd's logic. I could just walk the content and replace the `define` with a `stealModule.exports` and not have to worry about the context of the "factory" function, but I'll have to detect and remove the conditional around the `define` otherwise it won't eval correctly on the browser.

```js
[
  "jquery",
  function(stealRequire, stealExports, stealModule) {
    (function() {})(window, function(global) {
      var jQuery = {};

      if (window.define && define.amd) {
        stealModule.exports = function() {
          return jQuery;
        };
      }

      return jQuery;
    });
  }
];
```

Another idea would be to see the module and detect if it's a huge IIFE and transpile it to 


```js
[
  "jquery",
  function(stealRequire, stealExports, stealModule) {
    stealModule.exports = IIFE;
  }
]
```

thoughts?

**Comment by m-mujica** [comment]
> I think a slim version of that would be:

```js
[
  "jquery",
  function(stealRequire, stealExports, stealModule) {
    stealModule.exports = (function() {
		// eval jquery's content somehow and return it?
    })(window);
  }
]
```

Sounds good, doesn't work.

**Comment by m-mujica** [comment]
I'll try with this approach, only for top level IIFE.... in order to get around the amd detection, we'll have to replace the `define` identifiers that are not CallExpressions with `stealRequire` and set `stealRequire.amd` to true.

```js
[
  "jquery",
  function(stealRequire, stealExports, stealModule) {
    (function() {})(window, function(global) {
      var jQuery = {};

      if (window.define && define.amd) {
        stealModule.exports = function() {
          return jQuery;
        };
      }

      return jQuery;
    });
  }
];
```

**Comment by justinbmeyer** [comment]
Could we use something like what system JS is doing for globals?

**Comment by matthewp** [comment]
@m-mujica you could also add a tiny amd shim to modules which work this way (having the define() deep within the code), something like `define = function(a, b, c) { stealModule.exports = c() }); define.amd = true` would that work?
