### ISSUE TITLE
Support Babel's AMD to SLIM 

### ISSUE THREAD

**Issue by m-mujica** [stealjs/transpile#88]

**Comment by m-mujica** [comment]
@matthewp as you said, I think we only need to take insert the source body content into the slim function, also:

1) turn `load.meta.deps` into `stealRequires`
2) turn `load.meta.exports` into `stealExports["PROP"] = PROP`

anything else?

**Comment by matthewp** [comment]
nope, that sounds right to me.

**Comment by matthewp** [comment]
Wait, is this the right issue, you're talking about global->slim i think

**Comment by m-mujica** [comment]
lol, Manuel go home, you're drunk... Yeah
